export const USERS_LOADING = 'USERS_LOADING'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'