// chats
export const CHAT_INITIAL_LOADING = 'CHAT_INITIAL_LOADING'
export const CHAT_INITIAL_LOADED = 'CHAT_INITIAL_LOADED'
export const CHAT_LOADED = 'CHAT_LOADED'
export const CHAT_ADDING = 'CHAT_ADDING'
export const CHAT_ADD_SUCCESS = 'CHAT_ADD_SUCCESS'
export const CHAT_ADD_ERROR = 'CHAT_ADD_ERROR'
export const CHAT_LOGOUT = 'CHAT_LOGOUT'

// messages
export const CHAT_SENDING_MESSAGE = 'CHAT_SENDING_MESSAGE'
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS'
export const CHAT_SEND_MESSAGE_ERROR = 'CHAT_SEND_MESSAGE_ERROR'
export const CHAT_MESSAGE_UPDATE_TEXT = 'CHAT_MESSAGE_UPDATE_TEXT'
export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'