// chats
export const CHAT_ADDING_CHAT = 'CHAT_ADDING_CHAT'
export const CHAT_ADD_CHAT_SUCCESS = 'CHAT_ADD_CHAT_SUCCESS'
export const CHAT_ADD_CHAT_ERROR = 'CHAT_ADD_CHAT_ERROR'
export const CHAT_LOAD_CHATS_SUCCESS = 'CHAT_LOAD_CHATS_SUCCESS'
export const CHAT_LOAD_CHATS_ERROR = 'CHAT_LOAD_CHATS_ERROR'

// messages
export const CHAT_SENDING_MESSAGE = 'CHAT_SENDING_MESSAGE'
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS'
export const CHAT_SEND_MESSAGE_ERROR = 'CHAT_SEND_MESSAGE_ERROR'
export const CHAT_MESSAGE_UPDATE_TEXT = 'CHAT_MESSAGE_UPDATE_TEXT'
export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'